package com.northsunstrider.entity;
// Generated 2017-10-26 13:17:20 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SgsHero generated by hbm2java
 */
@Entity
@Table(name = "sgs_hero", catalog = "test_db")
public class SgsHero implements java.io.Serializable {

	private Long id;
	private String name;
	private int force;
	private int health;
	private Set<SgsSkill> sgsSkills = new HashSet<SgsSkill>(0);

	public SgsHero() {
	}

	public SgsHero(String name, int force, int health) {
		this.name = name;
		this.force = force;
		this.health = health;
	}

	public SgsHero(String name, int force, int health, Set<SgsSkill> sgsSkills) {
		this.name = name;
		this.force = force;
		this.health = health;
		this.sgsSkills = sgsSkills;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "force_", nullable = false)
	public int getForce() {
		return this.force;
	}

	public void setForce(int force) {
		this.force = force;
	}

	@Column(name = "health", nullable = false)
	public int getHealth() {
		return this.health;
	}

	public void setHealth(int health) {
		this.health = health;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sgsHero")
	public Set<SgsSkill> getSgsSkills() {
		return this.sgsSkills;
	}

	public void setSgsSkills(Set<SgsSkill> sgsSkills) {
		this.sgsSkills = sgsSkills;
	}

}
